import { Platform, StyleSheet } from 'react-native';
import { Colors, Fonts } from 'theme';
import { scaleHeight, scaleWidth } from 'utils';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    // paddingHorizontal: 20,
    backgroundColor: Colors.main,
    borderWidth: 1,
    borderColor: Colors.neonViolet,
  },
  midFocus: {
    alignSelf: 'center',
    marginVertical: 20,
  },
  btnGender: {
    backgroundColor: 'white',
    borderRadius: 12,
    paddingVertical: 10,
    width: 120,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  input: {
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 15 : 0,
    color: 'white',
    fontFamily: Fonts.medium,
    backgroundColor: Colors.main,
    height: 48,
    flex: 1,
    marginBottom: 10,
    shadowColor: Colors.neonViolet,
    borderWidth: 2,
    borderColor: Colors.neonViolet,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  btnForm: {
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: Platform.OS === 'android' ? 15 : 5,
    backgroundColor: Colors.main,
    height: 48,
    flex: 1,
    marginBottom: 20,
    shadowColor: Colors.neonViolet,
    borderWidth: 2,
    borderColor: Colors.neonViolet,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  placeholder: {},
  btnNext: {
    borderRadius: 12,
    backgroundColor: 'white',
    paddingVertical: 10,
    paddingHorizontal: 20,
    width: scaleWidth(70),
    height: 48,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  heightContainer: {
    marginHorizontal: 15,
  },
  button: {
    borderRadius: 12,
    backgroundColor: Colors.neonViolet,
    paddingVertical: 15,
    width: 150,
    alignSelf: 'center',
    alignItems: 'center',
    shadowOffset: {
      width: 1,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 3,
  },
  shadow: {
    shadowColor: Colors.neonViolet,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 0.2,
    elevation: 3,
  },
  error: {
    marginBottom: 15,
    fontFamily: Fonts.medium,
    color: 'white',
  },
  subtitle: {
    fontFamily: Fonts.semibold,
    marginBottom: 10,
    fontSize: 16,
  },
  planContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.main,
    borderRadius: 12,
    padding: 15,
    minHeight: 300,
    borderWidth: 2,
    borderColor: Colors.neonViolet,
  },
  planSelect: {
    backgroundColor: Colors.darkLavener,
  },
  planSelectTxt: {
    color: 'white',
  },
  label: {
    color: 'white',
    marginBottom: 10,
  },
  textGender: {
    fontSize: 15,
    textAlign: 'center',
    fontFamily: Fonts.medium,
    top: -2,
  },
});
